os: windows
language: C++
branches:
  only:
  - master
  - 0.1.0
  - 0.2
  - ci_check
before_install:
  - wget -q https://download.qt.io/official_releases/qt/5.13/5.13.2/qt-opensource-windows-x86-5.13.2.exe
install:
  - choco install golang
  - choco install yasm
  - ./qt-opensource-windows-x86-5.13.2.exe --script ./.ci/qt_installer_windows.qs
script:
  - mkdir build
  - cd build
  - setx GOROOT "c:\Go"
  - setx path "%path%;C:\Qt\5.13.2\msvc2017\bin;C:\Go\bin;C:\ProgramData\chocolatey\lib\yasm\tools"
  - set GOROOT="c:\Go"
  - set PATH="%PATH%;C:\Qt\5.13.2\msvc2017\bin;C:\Go\bin;C:\ProgramData\chocolatey\lib\yasm\tools"
  - cmake -DCMAKE_PREFIX_PATH="C:\Qt\5.13.2\msvc2017;C:\Go\bin;C:\ProgramData\chocolatey\lib\yasm\tools" ..
  - cmake --build .
  - ctest -C DEBUG -E qtgrpc_*
