// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: simpletest.proto

#include "simpletest.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace qtprotobufnamespace {
namespace tests {
class SimpleStringMessageDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SimpleStringMessage>
      _instance;
} _SimpleStringMessage_default_instance_;
}  // namespace tests
}  // namespace qtprotobufnamespace
namespace protobuf_simpletest_2eproto {
static void InitDefaultsSimpleStringMessage() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::qtprotobufnamespace::tests::_SimpleStringMessage_default_instance_;
    new (ptr) ::qtprotobufnamespace::tests::SimpleStringMessage();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::qtprotobufnamespace::tests::SimpleStringMessage::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_SimpleStringMessage =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsSimpleStringMessage}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_SimpleStringMessage.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qtprotobufnamespace::tests::SimpleStringMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::qtprotobufnamespace::tests::SimpleStringMessage, testfieldstring_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::qtprotobufnamespace::tests::SimpleStringMessage)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::qtprotobufnamespace::tests::_SimpleStringMessage_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "simpletest.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020simpletest.proto\022\031qtprotobufnamespace."
      "tests\".\n\023SimpleStringMessage\022\027\n\017testFiel"
      "dString\030\006 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 101);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "simpletest.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_simpletest_2eproto
namespace qtprotobufnamespace {
namespace tests {

// ===================================================================

void SimpleStringMessage::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SimpleStringMessage::kTestFieldStringFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SimpleStringMessage::SimpleStringMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_simpletest_2eproto::scc_info_SimpleStringMessage.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:qtprotobufnamespace.tests.SimpleStringMessage)
}
SimpleStringMessage::SimpleStringMessage(const SimpleStringMessage& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  testfieldstring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.testfieldstring().size() > 0) {
    testfieldstring_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.testfieldstring_);
  }
  // @@protoc_insertion_point(copy_constructor:qtprotobufnamespace.tests.SimpleStringMessage)
}

void SimpleStringMessage::SharedCtor() {
  testfieldstring_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

SimpleStringMessage::~SimpleStringMessage() {
  // @@protoc_insertion_point(destructor:qtprotobufnamespace.tests.SimpleStringMessage)
  SharedDtor();
}

void SimpleStringMessage::SharedDtor() {
  testfieldstring_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SimpleStringMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* SimpleStringMessage::descriptor() {
  ::protobuf_simpletest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_simpletest_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SimpleStringMessage& SimpleStringMessage::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_simpletest_2eproto::scc_info_SimpleStringMessage.base);
  return *internal_default_instance();
}


void SimpleStringMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:qtprotobufnamespace.tests.SimpleStringMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  testfieldstring_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SimpleStringMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:qtprotobufnamespace.tests.SimpleStringMessage)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string testFieldString = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_testfieldstring()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->testfieldstring().data(), static_cast<int>(this->testfieldstring().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "qtprotobufnamespace.tests.SimpleStringMessage.testFieldString"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:qtprotobufnamespace.tests.SimpleStringMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:qtprotobufnamespace.tests.SimpleStringMessage)
  return false;
#undef DO_
}

void SimpleStringMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:qtprotobufnamespace.tests.SimpleStringMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string testFieldString = 6;
  if (this->testfieldstring().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->testfieldstring().data(), static_cast<int>(this->testfieldstring().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qtprotobufnamespace.tests.SimpleStringMessage.testFieldString");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->testfieldstring(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:qtprotobufnamespace.tests.SimpleStringMessage)
}

::google::protobuf::uint8* SimpleStringMessage::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:qtprotobufnamespace.tests.SimpleStringMessage)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string testFieldString = 6;
  if (this->testfieldstring().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->testfieldstring().data(), static_cast<int>(this->testfieldstring().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "qtprotobufnamespace.tests.SimpleStringMessage.testFieldString");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->testfieldstring(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:qtprotobufnamespace.tests.SimpleStringMessage)
  return target;
}

size_t SimpleStringMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:qtprotobufnamespace.tests.SimpleStringMessage)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string testFieldString = 6;
  if (this->testfieldstring().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->testfieldstring());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SimpleStringMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:qtprotobufnamespace.tests.SimpleStringMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const SimpleStringMessage* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SimpleStringMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:qtprotobufnamespace.tests.SimpleStringMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:qtprotobufnamespace.tests.SimpleStringMessage)
    MergeFrom(*source);
  }
}

void SimpleStringMessage::MergeFrom(const SimpleStringMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:qtprotobufnamespace.tests.SimpleStringMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.testfieldstring().size() > 0) {

    testfieldstring_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.testfieldstring_);
  }
}

void SimpleStringMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:qtprotobufnamespace.tests.SimpleStringMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SimpleStringMessage::CopyFrom(const SimpleStringMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:qtprotobufnamespace.tests.SimpleStringMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SimpleStringMessage::IsInitialized() const {
  return true;
}

void SimpleStringMessage::Swap(SimpleStringMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SimpleStringMessage::InternalSwap(SimpleStringMessage* other) {
  using std::swap;
  testfieldstring_.Swap(&other->testfieldstring_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata SimpleStringMessage::GetMetadata() const {
  protobuf_simpletest_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_simpletest_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tests
}  // namespace qtprotobufnamespace
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::qtprotobufnamespace::tests::SimpleStringMessage* Arena::CreateMaybeMessage< ::qtprotobufnamespace::tests::SimpleStringMessage >(Arena* arena) {
  return Arena::CreateInternal< ::qtprotobufnamespace::tests::SimpleStringMessage >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
